#!/bin/bash

# Récupération du repo s'il n'existe pas déjà
cd
mkdir -p git
cd git
git clone https://github.com/yaap7/miSCripts || cd miSCripts && git pull
cd

# création des liens symboliques
mkdir -p bin
cd bin
ln -s ~/git/miSCripts/tiny_scripts/clean-conf ./
ln -s ~/git/miSCripts/tiny_scripts/colorize ./
ln -s ~/git/miSCripts/grep-hash-ntlm ./
ln -s ~/git/miSCripts/tiny_scripts/grep-ip ./
ln -s ~/git/miSCripts/tiny_scripts/grep-ip.py ./
ln -s ~/git/miSCripts/tiny_scripts/grep-iprange ./
ln -s ~/git/miSCripts/tiny_scripts/grep-uuid ./
ln -s ~/git/miSCripts/tiny_scripts/jwt-decode ./
ln -s ~/git/miSCripts/new-shell ./
ln -s ~/git/miSCripts/tiny_scripts/ntlmsum ./
ln -s ~/git/miSCripts/recon-ip ./
ln -s ~/git/miSCripts/tiny_scripts/remove-bom ./
ln -s ~/git/miSCripts/tiny_scripts/remove-escape-sequences ./
ln -s ~/git/miSCripts/tiny_scripts/split-lines ./
ln -s ~/git/miSCripts/tiny_scripts/tolower ./
ln -s ~/git/miSCripts/tiny_scripts/toupper ./
ln -s ~/git/miSCripts/tiny_scripts/uncolorize ./
ln -s ~/git/miSCripts/tiny_scripts/convert-jpg-to-webp ./
ln -s ~/git/miSCripts/optimize-img ./
ln -s ~/git/miSCripts/reduce-picture-from-android ./

# Ajout d'une petite conf dans le bashrc
cat >> ~/.bashrc << EOF
# added by ggr from make-myself-home
shopt -s histappend
export HISTCONTROL=ignoredups:erasedups
export PATH="\$HOME/bin:\$HOME/.local/bin:\$PATH"

get_git_branch() {
     git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \\(.*\\)/(\\1)/'
}

if [[ \$(id -u) -eq "0" ]] ; then
    export PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;31m\]\u\[\033[00m\]@'
else
    export PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[00;32m\]\u\[\033[00m\]@'
fi
if [[ -z "\${SSH_CONNECTION}" ]] ; then
    export PS1="\${PS1}"'\[\033[00;37m\]\h\[\033[00m\]:\[\033[00;34m\]\w\[\033[00m\] '"\\\$(get_git_branch)"'$ '
else
    export PS1="\${PS1}"'\[\033[01;36m\]\h\[\033[00m\]:\[\033[00;34m\]\w\[\033[00m\] '"\\\$(get_git_branch)"'$ '
fi

if [[ -d ~/.bash_completions ]] ; then
    for f in ~/.bash_completions/*.bash ; do
        source "\$f"
    done
fi

alias l="ls -lh --color=auto"
alias ll="ls -alh --color=auto"
alias grep="grep --color"
alias clean-conf="sed -e 's/#.*//g' | grep -v '^[[:blank:]]*$'"
alias grep-ip="grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'"
alias uncolorize='sed "s/\x1b[^m]*m//g"'
alias tolower="tr '[[:upper:]]' '[[:lower:]]'"
alias toupper="tr '[[:lower:]]' '[[:upper:]]'"
alias ip="ip --color"
alias ipb="ip --color --brief"
alias curl-headerdump='curl -D - -s -o /dev/null'
alias copy='xclip -selection c'
alias gs="git status"

EOF
