#!/bin/bash

cd
mkdir -p tools
cd tools
git clone https://github.com/yaap7/miSCripts || cd miSCripts && git pull
cd

mkdir -p bin
cd bin
wget "https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip"
unzip "exa-linux-x86_64-0.9.0.zip"
mv "exa-linux-x86_64" "exa"
ln -s ~/tools/miSCripts/tiny_scripts/clean-conf ./
ln -s ~/tools/miSCripts/tiny_scripts/colorize ./
ln -s ~/tools/miSCripts/grep-hash-ntlm ./
ln -s ~/tools/miSCripts/tiny_scripts/grep-ip ./
ln -s ~/tools/miSCripts/tiny_scripts/grep-ip.py ./
ln -s ~/tools/miSCripts/tiny_scripts/grep-iprange ./
ln -s ~/tools/miSCripts/tiny_scripts/grep-uuid ./
ln -s ~/tools/miSCripts/tiny_scripts/jwt-decode ./
ln -s ~/tools/miSCripts/new-shell ./
ln -s ~/tools/miSCripts/tiny_scripts/ntlmsum ./
ln -s ~/tools/miSCripts/recon-ip ./
ln -s ~/tools/miSCripts/tiny_scripts/remove-bom ./
ln -s ~/tools/miSCripts/tiny_scripts/remove-escape-sequences ./
ln -s ~/tools/miSCripts/tiny_scripts/split-lines ./
ln -s ~/tools/miSCripts/tiny_scripts/tolower ./
ln -s ~/tools/miSCripts/tiny_scripts/toupper ./
ln -s ~/tools/miSCripts/tiny_scripts/uncolorize ./

cat >> ~/.bashrc << EOF

shopt -s histappend
export HISTCONTROL=ignoredups:erasedups
export PATH="\$HOME/bin:\$HOME/.local/bin:\$PATH"

if [[ \$(id -u) -eq "0" ]] ; then
    export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u\[\033[00m\]@'
else
    export PS1='${debian_chroot:+($debian_chroot)}\[\033[00;32m\]\u\[\033[00m\]@'
fi
if [[ -z "${SSH_CONNECTION}" ]] ; then
    export PS1="\${PS1}"'\[\033[00;37m\]\h\[\033[00m\]:\[\033[00;34m\]\w\[\033[00m\]\$ '
else
    export PS1="\${PS1}"'\[\033[01;36m\]\h\[\033[00m\]:\[\033[00;34m\]\w\[\033[00m\]\$ '
fi

alias l="ls -lh --color=auto"
alias ll="ls -alh --color=auto"
alias grep="grep --color"
alias clean-conf="sed -e 's/#.*//g' | grep -v '^[[:blank:]]*$'"
alias grep-ip="grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'"
alias uncolorize='sed "s/\x1b[^m]*m//g"'
alias tolower="tr '[[:upper:]]' '[[:lower:]]'"
alias toupper="tr '[[:lower:]]' '[[:upper:]]'"
alias ip="ip --color"
alias ipb="ip --color --brief"
alias curl-headerdump='curl -D - -s -o /dev/null'

# funky prompt
# PS1="\[\033[0;31m\]\342\224\214\342\224\200\\\$([[ \\\$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[\$(if [[ \${EUID} == 0 ]]; then echo '\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h'; else echo '\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h'; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\[\033[0m\]\[\e[01;33m\]\\\\$\[\e[0m\] "

# funky ls
# hash exa 2>/dev/null && alias l='exa -l --git --time-style iso' && alias ll='exa -a -l --git --time-style iso'

EOF
