#!/bin/bash

# usage:
#   nmap-extract-tcp-ports-to-list *.gnmap
# or
#   cat nmap/* | nmap-extract-tcp-ports-to-list

cat $@ - | grep -o '[0-9]*/open/tcp' | cut -d'/' -f1 | sort -nu | tr '\n' ',' | head -c -1
echo
