#!/bin/bash

# prerequisites:
# * jpegoptim
# * pngquant

while [[ "$#" -gt "0" ]] ; do
	img="$1"
	if file -i "$img" | grep -q -e 'image/jpeg;' -e 'image/png' ; then
		cp "$img" "${img}.old"
		if file -i "$img" | grep -q 'image/jpeg;' ; then
			jpegoptim -q -s "${img}"
		elif file -i "${img}" | grep -q 'image/png;' ; then
			pngquant --ext=.png --force --strip "$img"
		fi
		# display effective gain
		si="$(stat -c '%s' "${img}.old")"
		sf="$(stat -c '%s' "${img}")"
		if [[ "$sf" -eq "$si" ]] ; then
			echo "$img was already optimized."
			rm "${img}.old"
		elif [[ "$sf" -gt "$si" ]] ; then
			echo "Error: $img is now bigger! Reverting..." >&2
			mv "${img}.old" "${img}"
		else
			percent="$(( ($si - $sf) * 100 / $si))"
			echo "$img reduced by ${percent}% (${si} → ${sf})"
			rm "${img}.old"
		fi
	else
		echo "$img not valid for optimisation (jpeg/png)" >&2
	fi
	shift
done
