#!/bin/bash

while [[ "$#" -gt 0 ]] ; do
    if echo "$1" | grep -q '\.jpg$' ; then
        # skip the conversion if the webp already exists
        if [[ ! -f "${1%.jpg}.webp" ]] ; then
            cwebp -quiet -o "${1%.jpg}.webp" "$1"
        fi
    else
        echo "I only work with .jpg files (got ${1})"
    fi
    shift
done
