#!/bin/bash

if [[ $# -ne "1" ]] ; then
    echo "Usage $0 <file_to_install.png>" >&2
    exit 1
fi

img="$(basename "$1")"

for icon_dir in "${HOME}"/.local/share/icons/hicolor/*x* ; do 
    size="$(echo "$icon_dir" | grep -o "[0-9]*x[0-9]*")"
    convert "$1" -resize "${size}"\! "${icon_dir}/${img}"
    if which pngquant >/dev/null ; then
        pngquant --skip-if-larger --strip --output "${icon_dir}/${img}.opti" "${icon_dir}/${img}" && \
        mv "${icon_dir}/${img}.opti" "${icon_dir}/${img}"
    fi
done

